# Generated by Django 2.2.16 on 2020-11-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='name',
            new_name='poll_name',
        ),
    ]
