# Generated by Django 2.2.16 on 2020-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0004_auto_20201114_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=200),
        ),
    ]
