# Generated by Django 2.2.16 on 2020-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0007_auto_20201114_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
