# Generated by Django 2.2.16 on 2020-11-15 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0012_auto_20201114_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='str_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Помните: Если опрос по времени стартанул - то изменить его уже нельзя будет', verbose_name='Время старта опроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(verbose_name='Время окончания опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_description',
            field=models.CharField(max_length=200, verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(max_length=200, verbose_name='Название опроса'),
        ),
    ]
