# Generated by Django 2.2.16 on 2020-11-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0013_auto_20201115_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_description',
            field=models.TextField(verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(help_text='Не более 200 символов', max_length=200, verbose_name='Название опроса'),
        ),
    ]
