# Generated by Django 2.2.16 on 2020-11-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0015_auto_20201115_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(help_text='Укажите, когда перестанет быть активным опрос', verbose_name='Время окончания опроса'),
        ),
    ]
