# Generated by Django 2.2.16 on 2020-11-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0016_auto_20201115_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(verbose_name='Время окончания опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='str_date',
            field=models.DateTimeField(help_text='Помните: Если опрос по времени стартанул - то изменить его уже нельзя будет', verbose_name='Время старта опроса'),
        ),
    ]
