# Generated by Django 2.2.16 on 2020-11-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0019_auto_20201115_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='app_polls.Choice', verbose_name='Выбрать ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ текстом'),
        ),
    ]
