# Generated by Django 2.2.16 on 2020-11-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0022_auto_20201115_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_one',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Choice', verbose_name='Выбрать ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Ответ текстом'),
            preserve_default=False,
        ),
    ]
