# Generated by Django 2.2.16 on 2020-11-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0025_auto_20201115_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_polls.Question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='options_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice_many',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice_one',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='options_many',
            field=models.ManyToManyField(blank=True, related_name='options_many', to='app_polls.Options', verbose_name='Несколько ответов'),
        ),
        migrations.AddField(
            model_name='answer',
            name='options_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Options', verbose_name='Выбрать ответ'),
        ),
    ]
