# Generated by Django 2.2.16 on 2020-11-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0026_auto_20201115_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='options_text',
            field=models.CharField(help_text='не более 100 символов', max_length=100, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_polls.Question', verbose_name='Вопрос'),
        ),
    ]
