# Generated by Django 2.2.16 on 2020-11-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0028_auto_20201115_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='poll_name',
        ),
    ]
