# Generated by Django 2.2.16 on 2020-11-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0029_auto_20201115_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll_name',
            new_name='poll',
        ),
    ]
