# Generated by Django 2.2.16 on 2020-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0030_auto_20201115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options_text',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Ответ текстом'),
        ),
    ]
