# Generated by Django 2.2.16 on 2020-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0031_auto_20201115_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ текстом'),
        ),
    ]
