# Generated by Django 2.2.16 on 2020-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0032_auto_20201116_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Аноним')),
                ('user_name', models.CharField(help_text='не более 100 символов', max_length=100, verbose_name='ФИО пользователя')),
                ('mail', models.CharField(help_text='не более 50 символов', max_length=50, verbose_name='Электронная почта')),
                ('number', models.CharField(help_text='не более 15 символов', max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_name',
        ),
    ]
