# Generated by Django 2.2.16 on 2020-11-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0033_auto_20201116_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, help_text='не более 50 символов', max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, help_text='не более 15 символов', max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, help_text='не более 100 символов', max_length=100, verbose_name='ФИО пользователя'),
        ),
    ]
