# Generated by Django 2.2.16 on 2020-11-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0034_auto_20201116_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app_polls.User', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
